from read_res import SWATreader
import pandas as pd
# Written by Qianyang Wang
# University of Alberta


def convert(swatdir,objpath,variables):
    """
    :param swatdir: The directory of the SWAT project
    :param variables: A list of variable names in SWAT Sub-basin result file (to be exported)
    """
    swatreader = SWATreader(swatdir)
    res = swatreader.read_sub()
    res = res.reset_index(names=["TIME"])
    lres = []
    for id,i in enumerate(variables):
        varres = res[i]
        if i == "WYLDmm":
            varres = varres * res["AREAkm2"] * 1000 / 86400
            variables[id] = "FLOW"
        if i == "SYLDt/ha":
            varres = varres * res["AREAkm2"] * 100000
            variables[id] = "SEDIMENTkg"
        varres = pd.DataFrame(varres,columns=["VALUE"])
        stations = res["SUB"].rename("STATION")
        stations = stations.map(lambda x: "Reach{}".format(x))
        dftime = res["TIME"]
        colvar = pd.DataFrame({"VARIABLE":[variables[id] for r in range(len(varres))]})
        varnew = pd.concat([dftime,stations,varres,colvar],axis=1)
        lres.append(varnew)
    db = pd.concat(lres,axis=0)
    db.to_excel(objpath,index=False)


def write_linkfile(flowfunc,extdb,out_path,varid=1,dbid=1):
    """
    :param flowfunc: The FlowFunc.xlsx file generated by SWATReachReader
    :param extdb: The generated External Database of SWAT result
    :param varid: Variable ID in WASP8 [1 ... ]
    :param dbid: Database ID in WASP8 [1 ... ]
    """
    df = pd.read_excel(flowfunc)
    dfres = pd.read_excel(extdb)
    rch_seq = df["Reach"]
    st_seq = sorted(dfres["STATION"].unique())
    meta = []
    for r in rch_seq:
        row = {"Data Source":dbid,"PCODE":varid,"Station ID":st_seq.index(r)+1}
        meta.append(row)
    dfout = pd.DataFrame(meta)
    dfout.to_excel(out_path)

if "__name__" == "__main__":
    # Example
    convert(r"D:\GrandSWATcal\process1","D:\GrandWasp\ExternalFlow.xlsx",variables=["WYLDmm"])
    write_linkfile(r"D:\GrandWasp\FlowFunc.xlsx",r"D:\GrandWasp\ExternalFlow.xlsx","D:\GrandWasp\ExternalLink.xlsx")